// Code generated by "stringer -linecomment -type=tokenType"; DO NOT EDIT.

package parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenEOF-0]
	_ = x[tokenError-1]
	_ = x[tokenFOUNDRY-2]
	_ = x[tokenFAMILY-3]
	_ = x[tokenWEIGHT-4]
	_ = x[tokenSLANT-5]
	_ = x[tokenWIDTH-6]
	_ = x[tokenSTYLE-7]
	_ = x[tokenDPI-8]
	_ = x[tokenSPACING-9]
	_ = x[tokenCHARSET_REGISTRY-10]
	_ = x[tokenCHARSET_ENCODING-11]
	_ = x[tokenCHAR-12]
	_ = x[tokenXOFF-13]
	_ = x[tokenYOFF-14]
	_ = x[tokenADVANCE-15]
	_ = x[tokenBitmapRow-16]
}

const _tokenType_name = "EOFerrorFOUNDRYFAMILYWEIGHTSLANTWIDTHSTYLEDPISPACINGCHARSET_REGISTRYCHARSET_ENCODINGCHARXOFFYOFFADVANCEbitmap row"

var _tokenType_index = [...]uint8{0, 3, 8, 15, 21, 27, 32, 37, 42, 45, 52, 68, 84, 88, 92, 96, 103, 113}

func (i tokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_tokenType_index)-1 {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[idx]:_tokenType_index[idx+1]]
}
